<?php include ('./template/parts/header.phtml'); ?>
        
    <main>
        <div class="bouton-accueil">
            <a href="index.php">Accueil</a>
        </div>
        
        <div class="bouton-connect">
            <a href="login.php">Connexion</a>
        </div>
        
        <div class="bouton-inscription">
            <a href="register.php">Inscription</a>
        </div>
        
    </header>
    
    <h1>Akinator Ultrakill</h1>
    
    <div class="bouton-connexion">
        <a href="login.php">Connectez-vous</a>
    </div>
</main>

<?php include ('./template/parts/footer.phtml'); ?>