<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Accueil</title>
    <link rel="stylesheet" href="./assets/css/accueil.css" type="text/css" />
</head>
<body>
    <header>
        
        <div class="bouton-accueil">
            <a href="index.php">Accueil</a>
        </div>
        
        <div class="bouton-connect">
            <a href="login.php">Connexion</a>
        </div>
        
        <div class="bouton-inscription">
            <a href="register.php">Inscription</a>
        </div>
        
    </header>
    
    <h1>Akinator Ultrakill</h1>
    
    <div class="bouton-connexion">
        <a href="login.php">Connectez-vous</a>
    </div>
</body>
</html>