<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Akinator</title>
</head>
<body>
    
        <!-- Inclusion du template de header -->
    <?php include_once './template/parts/header.phtml'; ?>

    <!-- Inclusion du template de page -->
    <?php include_once $template; ?>

    <!-- Inclusion du template de footer -->
    <?php include_once './template/parts/footer.phtml'; ?>


</body>
</html>