<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="css/login.css">
</head>
<body>
    <header>
        <a href="index.php">3WA Tasks</a>
    </header>
 
    <main>
        <div class="container">
            <h2>Login</h2>
           
                <?php if (!empty($error)) : ?>
                <p style="color:red"><?= $error ?></p>
            <?php endif; ?>
 
            <form method="post" action="login.php">
                <div class="field">
                    <label for="user_name">Username</label>
                    <input type="text" id="user_name" name="user_name" required>
                </div>
                <div class="field">
                    <label for="password">Password</label>
                    <input type="password" id="password" name="password" required>
                </div>
                <button type="submit">Login</button>
            </form>
        </div>
    </main>
 
    <footer>
        <p>©2024 - 3W Academy - All rights reserved</p>
    </footer>
</body>
</html>