<?php include ('./template/parts/header.phtml'); ?>
    <link rel="stylesheet" href="" type="text/css" />
    <main>
        <div class="container">
            <h2>Connexion</h2>
           
                <?php if (!empty($error)) : ?>
                <p style="color:red"><?= $error ?></p>
            <?php endif; ?>
 
            <form method="post" action="login.php">
                <div class="field">
                    <label for="user_name">Nom d'utilisateur</label>
                    <input type="text" id="user_name" name="user_name" required>
                </div>
                <div class="field">
                    <label for="password">Mot de passe</label>
                    <input type="password" id="password" name="password" required>
                </div>
                <button type="submit">Se connecter</button>
            </form>
        </div>
    </main>
 
<?php include ('./template/parts/footer.phtml'); ?>